source 'https://rubygems.org'

# Specify your gem's dependencies in estados-municipios-brasileiros.gemspec
gemspec

gem 'activerecord'
gem 'dotenv-rails', groups: [:development, :test]
gem 'pg'
gem 'rake', '~> 12.0'
gem "roo", "~> 2.8.0"
gem 'rspec', '~> 3.0'
gem 'standalone_migrations', '~> 5.2', '>= 5.2.7'
